### ISSUE TITLE
Real time refresh

### ISSUE THREAD

**Issue by willeppy** [wellsfletcher/PlanetariumPlace#3]
Right now have to refresh page to see edits other users make could be cool if these showed up automatically. Could likely be done with periodic async database pulls

**Comment by wellsfletcher** [comment]
I've been thinking about doing this, but it seems quite hard. Do you have any advice about how to do this?

I know the [Reddit place people](https://redditblog.com/2017/04/13/how-we-built-rplace/) used web sockets.

**Comment by willeppy** [comment]
Hm yeah I think they probably needed really good performance. How are you storing edits right now / which files is that in?

One simple idea would be to periodically refresh. Some code is being run on start up that gets the current state when I load the page. You could rerun this code every 30 seconds or something. You would need to wrap it in async calls so that you're only updating the state and not completely reloading the page

**Comment by willeppy** [comment]
I bet you could do this in react without having to touch web sockets (which would be a headache)

**Comment by wellsfletcher** [comment]
I implemented this using an SQL database that keeps track of the position, color, and timestamp of every pixel placed. It polls the database every 5 seconds and plays back changes with a 5 second delay. I'm gonna close the issue now
